import type { Metadata } from "next";
import { Header } from "@/components";
import { LayoutType } from "@/types";
import localFont from "next/font/local";
import LivescoresProvider from "@/context/livescores";
import GlobalProvider from "@/context/global";
import styles from "./layout.module.css";
import "./globals.css";

const segoeui = localFont({
  src: [
    {
      path: "../public/fonts/SegoeUI-Light.woff2",
      weight: "300",
    },
    {
      path: "../public/fonts/SegoeUI.woff2",
      weight: "400",
    },
    {
      path: "../public/fonts/SegoeUI-SemiBold.woff2",
      weight: "600",
    },
    {
      path: "../public/fonts/SegoeUI-Bold.woff2",
      weight: "700",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutType) {
  return (
    <html lang="en">
      <body className={segoeui.className}>
        <div className={styles.header}>
          <Header />
        </div>

        <GlobalProvider>
          <LivescoresProvider>{children}</LivescoresProvider>
        </GlobalProvider>
      </body>
    </html>
  );
}
