import { Header } from "@/components";
import "./globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";
import styles from "./layout.module.css";
import { LayoutType } from "@/types";

const segoeui = localFont({
  src: [
    {
      path: "../public/fonts/SegoeUI-Light.woff2",
      weight: "300",
    },
    {
      path: "../public/fonts/SegoeUI.woff2",
      weight: "400",
    },
    {
      path: "../public/fonts/SegoeUI-SemiBold.woff2",
      weight: "600",
    },
    {
      path: "../public/fonts/SegoeUI-Bold.woff2",
      weight: "700",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutType) {
  return (
    <html lang="en">
      <body className={segoeui.className}>
        <div className={styles.header}>
          <Header />
        </div>

        {children}
      </body>
    </html>
  );
}
